---
- name: "AWS inventory create"
  hosts: localhost
  tasks:

    - name: "Collect ec2 instance"
      amazon.aws.ec2_instance_info:
        region: ap-south-1
        filters: 
          "tag:Name": my-search-engine_EC2
          instance-state-name: [ "running"]
      register: ec2

    - name: "dynamic inventory IP"
      debug:
       msg: "instance ID : {{item.public_ip_address}}"
      with_items: "{{ec2.instances}}" 

    - name: "Add hosts to inventory"
      add_host:
        name: "{{item.public_ip_address}}"
        ansible_ssh_host: "{{item.public_ip_address}}"
        ansible_ssh_port: 22
        ansible_ssh_private_key_file: "local_key"
        groups: 
          - instances
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      with_items: "{{ec2.instances}}"

- name: "Instance configuration"
  become: true
  hosts: all
  vars_files:
    - vars.yml
  tasks:

     - name: "Service Install"
       yum:
        name: "{{service_install}}"
        state: present

     - name: "Service start"
       service:
        name: "{{item}}"
        state: started
        enabled: true
       with_items: "{{service_list}}"

     - name: "docker python module install"
       pip:
        name: docker
        state: present
      
     - name: "Docker network create"
       community.docker.docker_network:
        name: "{{ item }}"
        state: present
        ipam_driver: default
       with_items: "{{docker_network}}"

     - name: "Searxng container create"
       community.docker.docker_container:
        name: "searxng"
        image: searxng/searxng
        networks:
          - name: searxng
        env:
          BASE_URL: "http://{{host_url}}"
          INSTANCE_NAME: "{{instance}}" 
        volumes:
          - /var/searxng/:/etc/searxng/
        ports:
          - "80:8080"
      
     
